[[rule]]
schema = "test"
table = "go-mysql1"

# if index is empty, use table as default
index = "go-mysql1"

# if type is empty, use index as default
type = "go-mysql1"

    # custom MySQL field name <-> Elasticsearch field name
    [rule.mapping]
    name = "title"

[[rule]]
schema = "test"
table = "go-mysql2"
index = "go-mysql2"
type = "go-mysql2"

