# MySQL address, user and password
my_addr = "127.0.0.1:3306"
my_user = "root"
my_pass = ""

# Elasticsearch address
es_addr = "127.0.0.1:9200"

# Path to store data, like master.info, and dump MySQL data 
data_dir = "./var"

# pseudo server id like a slave 
server_id = 1001

# mysql or mariadb
flavor = "mysql"

# mysqldump execution path
mysqldump = "mysqldump"

# MySQL data source
[[source]]
schema = "test"

# Only below tables will be synced to Elasticsearch.
# I don't think it is necessary to sync all tables in a database.
tables = ["test_river"]

# Below is for special rule mapping
[[rule]]
schema = "test"
table = "test_river"
index = "river"
type = "river"

    # title is MySQL es_test field name, es_tiel is your customized name in Elasticsearch
    [rule.field]
    title = "es_title"

